import Head from "next/head";
import LandingPage from "../Components/LandingPage";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Good will</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <LandingPage />
      </section>
    </div>
  );
};

export default Home;
